version: '3.9'

services:
  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: auth-db
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - ecommerce-network
    volumes:
      - auth-db-data:/var/opt/mssql

  ecommerce-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-db
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - ecommerce-network
    volumes:
      - ecommerce-db-data:/var/opt/mssql

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=auth-db;Database=AuthDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - auth-db
    networks:
      - ecommerce-network

  coreapi:
    build:
      context: ./CoreApi
      dockerfile: Dockerfile
    container_name: coreapi
    ports: 
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ecommerce-db;Database=CoreDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - ecommerce-db
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - authservice
      - coreapi
    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  auth-db-data:
  ecommerce-db-data:
