apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-db
spec:
  selector:
    app: ecommerce-db
  ports:
    - port: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-db
  template:
    metadata:
      labels:
        app: ecommerce-db
    spec:
      containers:
        - name: ecommerce-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: SA_PASSWORD
              value: "YourStrongPassword123!"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldata
          persistentVolumeClaim:
            claimName: ecommerce-db-pvc
metadata:
  name: ecommerce-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-db
  template:
    metadata:
      labels:
        app: ecommerce-db
    spec:
      securityContext:        
        runAsUser: 10001
        runAsGroup: 0
        fsGroup: 10001
      containers:
        - name: ecommerce-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: SA_PASSWORD
              value: "YourStrongPassword123!"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldata
          persistentVolumeClaim:
            claimName: ecommerce-db-pvc
