piVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ecommerce-ingress.ecommerce.proyectoredes.site
    secretName: tls-secret
  rules:
  - host: ecommerce-ingress.ecommerce.proyectoredes.site
  - http:
      paths:
      - path: /Auth/
        pathType: Prefix
        backend:
          service:
            name: authservice
            port:
              number: 8080
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: coreapi
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
